---
title: "CC para resíduos AR(1)"
output:
  html_document:
    df_print: paged
    theme: paper
    highlight: tango
    toc: true
    toc_float:
      collapsed: true
    code_folding: hide
    css:
      - ./web/styles.css
---

```{r echo=TRUE, message=FALSE, warning=FALSE}
Sys.setenv(lang = "en_US")
set.seed(1)
```


```{r include-html, message=FALSE, include=FALSE}
library(htmltools, quietly = T, warn.conflicts = F)
includeHTML("web/modal.html")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2, quietly = T, warn.conflicts = F)
library(forecast, quietly = T, warn.conflicts = F) # plot ts objects
library(knitr, quietly = T, warn.conflicts = F)
library(grid, quietly = T, warn.conflicts = F) # textGrob
library(gridExtra, quietly = T, warn.conflicts = F) # grid.arrange
library(latex2exp, quietly = T, warn.conflicts = F) # latex expressions
library(tidyr, quietly = T, warn.conflicts = F)
library(dplyr, quietly = T, warn.conflicts = F)

source("scripts/arima_funcs.R")
source("scripts/plot_themes.R")
source("scripts/amostras.R")
```

```{r}
knitr::opts_chunk$set(
  out.height = "\\textheight",
  out.width = "\\textwidth",
  out.extra = 'keepaspectratio=true class="chart-image"',
  fig.align = "center"
)

```


## Série para criação dos limites de controle

```{r}
set.seed(1)


amostra_inicial$modelo
```
```{r}
grid.arrange(
  autoplot(amostra_inicial$serie) + ggtitle("Série simulada para criação dos limites de controle") + theme.base + theme.ts,
  ggAcf(amostra_inicial$serie) + ggtitle("ACF da série simulada") + theme.base,
  ggPacf(amostra_inicial$serie) + ggtitle("PACF da série simulada") + theme.base,
  layout_matrix = rbind(c(1, 1), c(2, 3))
)
```


```{r}
grid.arrange(
  autoplot(amostra_inicial$residuos) + ggtitle("Resíduos do modelo AR(1)") + theme.base + theme.ts,
  ggAcf(amostra_inicial$residuos) + ggtitle("ACF dos resíduos") + theme.base,
  ggPacf(amostra_inicial$residuos) + ggtitle("PACF dos resíduos") + theme.base,
  layout_matrix = rbind(c(1, 1), c(2, 3))
)
```

### Limites de controle


```{r message=FALSE, warning=FALSE}
alpha <- 0.05
max_devio <- qnorm(1 - alpha/2) * amostra_inicial$sd_res
limites <- mean(amostra_inicial$residuos) + c(-max_devio, max_devio)

tabela_estatisticas_residuos <- function() {
  tabela <- data.frame(
    "mean" = amostra_inicial$media_res,
    "sd" = amostra_inicial$sd_res,
    "IL" = limites[1],
    "SL" = limites[2]
  )
  colnames(tabela) <- c("Média", "Desvio padrão", "Limite inferior", "Limite superior")
  t(tabela)
}

knitr::kable(
  tabela_estatisticas_residuos(),
  caption = "Intervalo de confiança dos resíduos",
  align = 'c',
  digits = 3
)
```


## Simulações

Amostras subsequentes para $\phi_0 \in \{0, 0.1, 0.2, \ldots, 0.8\}$ com $n = 200$.


```{r, fig.height = 10}
graficos_series <- function(dados) {
  lista <- c()
  for (i in 1:(n_simulacoes)) {
    lista[[i]] <- autoplot(amostras_subsequentes[[i]]) +
      ggtitle(TeX(sprintf("$\\phi_0=%.1f$", phi_0_para_amostras_seguintes[i]))) +
      theme.base +
      theme.no_axis_title
  }
  lista
}

graficos_resid <- function(dados) {
  lista <- c()
  for (i in 1:(n_simulacoes)) {
    lista[[i]] <- ggAcf(amostras_subsequentes[[i]]) +
      ggtitle(TeX(sprintf("$\\phi_0=%.1f$", phi_0_para_amostras_seguintes[i]))) +
      theme.base +
      theme.no_axis_title
  }
  lista
}

grid.arrange(
  grobs = (
    \() {
      lista_graficos <- c()
      
      # Séries
      lista_graficos[[2]] <- textGrob("Séries", gp = gpar(fontface = "bold", fontsize = 12))
      lista_graficos[[3]] <- textGrob("")
      lista_graficos <- c(lista_graficos, graficos_series(amostras_subsequentes))
      
      # Resíduos
      lista_graficos[[length(lista_graficos) + 2]] <- textGrob("ACFs", gp = gpar(fontface = "bold", fontsize = 12))
      lista_graficos[[length(lista_graficos) + 1]] <- textGrob("")
      lista_graficos <- c(lista_graficos, graficos_resid(amostras_subsequentes))
      lista_graficos
    }
  )(),
  ncol = 3,
  widths = c(1, 1, 1)
)

```

## Cartas de controle para os resíduos


```{r}
residuos_subsequentes <- lapply(amostras_subsequentes, function(amostra) Arima(amostra, model = amostra_inicial$modelo)$residuals)

cartas_controle <- function(dados) {
  lista <- c()
  for (i in 1:(n_simulacoes)) {
    residuos <- residuos_subsequentes[[i]]
    resid_layer <- autolayer(residuos_subsequentes[[i]])
    fora_de_controle = resid_layer$layer_data() %>% filter(seriesVal < limites[1] | seriesVal > limites[2])
    
    lista[[i]] <- autoplot(residuos) +
      geom_hline(yintercept = limites, linetype = "dashed", color = "red", alpha = 0.6) +
      geom_point(data = fora_de_controle, aes(x = timeVal, y = seriesVal), color = "red") +
      theme.base +
      theme.no_axis_title +
      theme(legend.position = "none") +
      labs(x = "Resíduos", y = "Observação") +
      ggtitle(TeX(sprintf("$\\phi_0=%.1f$", phi_0_para_amostras_seguintes[i])))
  }
  lista
}

grid.arrange(
  grobs = (
    \() {
      lista_graficos <- c()
      lista_graficos[[2]] <- textGrob("Resíduos", gp = gpar(fontface = "bold", fontsize = 12))
      lista_graficos[[3]] <- textGrob("")
      lista_graficos <- c(lista_graficos, cartas_controle(amostras_subsequentes))
      lista_graficos
    }
  )(),
  ncol = 3,
  widths = c(1, 1, 1)
)
```

### Quantidade de amostras fora de controle para cada $\phi_0$

```{r results = 'asis'}
quantidade_fora_de_controle <- sapply(residuos_subsequentes, function(residuos) {
  sum(residuos < limites[1] | residuos > limites[2])
})

tabela_estatisticas_amostras <- function() {
  tabela <- data.frame(
    "phi_0" = phi_0_para_amostras_seguintes,
    "fora" = quantidade_fora_de_controle,
    "prop" = 100 * quantidade_fora_de_controle / PARAMETROS$n_h1
  )
  colnames(tabela) <- c("$\\phi_0$", "Amostras fora de controle", "Proporção (%)")
  tabela
}

ggplot(tabela_estatisticas_amostras(), aes(x = `$\\phi_0$`, y = `Proporção (%)`)) +
  geom_point() +
  geom_line() +
  labs(x = TeX("$\\phi_0$"), y = "Porcentagem fora de controle") +
  ggtitle(TeX("Porcentagem de amostras fora de controle para cada $\\phi_0$")) +
  theme.base

kable(
  tabela_estatisticas_amostras(),
  caption = "Quantidade de amostras fora de controle para cada $\\phi_0$",
  align = 'c',
  digits = 3
)

```


