---
title: "CC para resíduos AR(1)"
output:
  html_document:
    df_print: paged
    theme: paper
    highlight: tango
    toc: true
    toc_float:
      collapsed: true
    code_folding: hide
    css:
      - ./web/styles.css
---

```{r echo=TRUE, message=FALSE, warning=FALSE}
Sys.setenv(lang = "en_US")
set.seed(1)
```


```{r include-html, message=FALSE, include=FALSE}
library(htmltools, quietly = T, warn.conflicts = F)
includeHTML("web/modal.html")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2, quietly = T, warn.conflicts = F)
library(forecast, quietly = T, warn.conflicts = F) # plot ts objects
library(knitr, quietly = T, warn.conflicts = F)
library(grid, quietly = T, warn.conflicts = F) # textGrob
library(gridExtra, quietly = T, warn.conflicts = F) # grid.arrange
library(latex2exp, quietly = T, warn.conflicts = F) # latex expressions
library(tidyr, quietly = T, warn.conflicts = F)
library(dplyr, quietly = T, warn.conflicts = F)
library(purrr, quietly = T, warn.conflicts = F)

source("scripts/arima_funcs.R")
source("scripts/plot_themes.R")
source("scripts/amostras.R")
```

```{r}
knitr::opts_chunk$set(
  out.height = "\\textheight",
  out.width = "\\textwidth",
  out.extra = 'keepaspectratio=true class="chart-image"',
  fig.align = "center"
)

```


```{r}
lambda_ <- 0.2
CL <- 3 * amostra_inicial$sd_res * sqrt(
  lambda_ * (1 - (1 - lambda_) ^ (2 * 1:PARAMETROS$n_h1)) / (2 - lambda_)
)

ewma_residuos <- amostras_df %>%
  group_by(phi) %>%
  summarise(
    observacao = list(1:length(serie)),
    serie = list(serie),
    residuos = list(residuos),
    ewma = map(residuos, ~ewma(.x, lambda = lambda_, x0 = amostra_inicial$xn)),
    LI = list(amostra_inicial$media_res - CL),
    LS = list(amostra_inicial$media_res + CL)
  ) %>%
  unnest(
    cols = c(observacao, serie, residuos, ewma, LI, LS)
  )
```

```{r}
ggplot(data = ewma_residuos) +
  geom_line(aes(x = observacao, y = LI, color = "Limite Inferior"), linetype = "dashed") +
  geom_line(aes(x = observacao, y = LS, color = "Limite Superior"), linetype = "dashed") +
  geom_line(aes(x = observacao, y = ewma, color = "EWMA")) +
  geom_point(data = . %>% filter(ewma < LI | ewma > LS),
             aes(x = observacao, y = ewma, color = "Fora de controle"), size = 2) +
  labs(x = "Observação", y = "Caracterísitca", color = "Legenda") +
  scale_color_manual(
    values = c(
      "Limite Inferior" = adjustcolor("red", alpha.f = 0.4),
      "Limite Superior" = adjustcolor("red", alpha.f = 0.4),
      "EWMA" = "black",
      "Fora de controle" = "red"
    )
  ) +
  labs(
    title = TeX("EWMA para resíduos AR(1)"),
  ) +
  theme.base +
  theme(
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  facet_wrap(~phi)
```

